list : list.o list_itr.o listTest.o list_functions.o
	gcc -o list -ansi -pedantic -Wall -g list.c list_itr.c listTest.c list_functions.c

list.o : list.c
	gcc -c -ansi -pedantic -Wall -g list.c

list_itr.o : list_itr.c
	gcc -c -ansi -pedantic -Wall -g list_itr.c

listTest.o : listTest.c
	gcc -c -ansi -pedantic -Wall -g listTest.c

list_functions.o : list_functions.c
	gcc -c -ansi -pedantic -Wall -g list_functions.c
