logTest : zlog4c.o testapp.o
	gcc -o logTest -g -pedantic -Wall -ansi zlog4c.o testapp.o
zlog4c.o : zlog4c.c
	gcc -c -g -pedantic -Wall -ansi zlog4c.c
testapp.o : testapp.c
	gcc -c -g -pedantic -Wall -ansi testapp.c
